name: Generate Date File
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Generate Rss
        run: |
          npm run build
      - name: Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated Rss Feed"
          git push
